default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: pguser
  password: pguser

development:
  <<: *default
  database: db/development

test:
  <<: *default
  database: db/test
  

production:
  <<: *default
  database: db/production